### ISSUE TITLE
Add .env to generated .gitignore file

### ISSUE THREAD

**Issue by nolawnchairs** [nestjs/schematics#1004]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not related to a problem.

### Describe the solution you'd like

The auto-generated .gitignore file ought to have .env included by default.

### What is the motivation / use case for changing the behavior?

The .env file is a common file in many projects that holds configuration data and secrets that oughtn't be checked into version control.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to address this issue?

**Comment by micalevisk** [comment]
@nolawnchairs you just need to change this: https://github.com/nestjs/nest-cli/blob/2271c9e0ba6be1c7a202ef1b67d81407a0ac26d5/lib/configuration/defaults.ts#L21 :smile_cat: 

---

@kamilmysliwiec this is at `nest-cli` side because somewhat `.gitignore` files aren't published to NPM

**Comment by micalevisk** [comment]
actually, this is already done. See:

https://github.com/nestjs/schematics/blob/93762c3f774fbbab57552753e3a960ad04d229a6/src/lib/application/files/js/.gitignore#L3-L4

https://github.com/nestjs/schematics/blob/93762c3f774fbbab57552753e3a960ad04d229a6/src/lib/application/files/ts/.gitignore#L3-L4

We just need to wait for the fix commented here: https://github.com/nestjs/nest-cli/pull/1630#discussion_r876589622 so `nest new` could generate those `.gitignore`
