### ISSUE TITLE
Improve compatibility with Nx

### ISSUE THREAD

**Issue by skreborn** [nestjs/schematics#105]
## I'm submitting a...
<pre><code>[ ] Regression
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request</code></pre>

## Current behavior
NestJS schematics are currently incompatible with Nx.

## Expected behavior
As per the [pull request](https://github.com/nrwl/nx/pull/807) by @FallenRiteMonk over at the Nx repository, NestJS should be compatible with Nx.

## What is the motivation / use case for changing the behavior?
@FrozenPandaz mentioned that they have reached out to @kamilmysliwiec regarding the above mentioned pull request, and that he has expressed interest in making this happen. Whether that comes to fruition is to be decided, but I was hoping to at least start a conversation, as both Nx and NestJS are invaluable assets to many of us.

## Environment
<pre><code>Nest version: 5.4.0</code></pre>

**Comment by kamilmysliwiec** [comment]
So basically, since the latest `@nestjs/schematics` release, we're fully customizable from outside and that was the main goal essentially. Now, you should be able to execute nest schematics using a normal schematics CLI as well as Angular CLI. Before, we had some issues with things like, for example, each generated element was automatically put inside a root directory (hardcoded `src`) by default, there were some errors about missing configuration options (inside exposed API interface) etc. Hence, previous schematics package in its form was not very flexible because too many crucial things were totally locked inside.

However, we got rid of these parts already, which means that packages like `nx` could potentially invoke nest schematics from its code easily now, without worrying about: (1) being up-to-date with Nest breaking changes (2) following best practices (3) updating schematics on its own and so on, and so on. And to be honest, this is actually everything what we can do on our side. Even though I'm personally using Nx (and I really enjoy it!), we cannot heavily integrate it with Nest CLI, because Nest is not being used only by Angular developers. It's successively used with React, Vue, and other technologies, and therefore we're not able to rely on a particular framework. We have to stay platform-agnostic, and thus, this feature (Nest integration in Nx) depends on Nx team now 🙂cc @FrozenPandaz

**Comment by kamilmysliwiec** [comment]
Working hard to push more detailed docs for the CLI asap

**Comment by FrozenPandaz** [comment]
This is awesome!

So I just tried this myself and was able to get it working albeit running into a few issues:

1. Nx needs to update to @angular/cli@~7.1.0
  a. This is in progress: https://github.com/nrwl/nx/pull/937
  b. This causes a weird issue where `node_modules/@nestjs/schematics/node_modules/@angular-devkit/schematics` tries to use some stuff from `node_modules/@angular-devkit/schematics`... I can't quite explain why.
  c. To prevent this in the future perhaps `@nestjs/schematics` should have a `peerDependency` on `@angular-devkit/schematics` and `@angular-devkit/core` and `@nestjs/cli` should bring in said dependencies?
2. NestJS schematics could still use more abstraction
  a. I think currently, the _ideal_ workflow (this currently is not smooth) for creating a NestJS application within Nx is the following:
```
# Create a workspace
create-nx-workspace my-workspace
# Add `@nestjs/schematics` to dependencies
yarn add @nestjs/schematics # Or perhaps: ng add @nestjs/schematics
# Create a node-app with no framework
ng g node-app nest-app --framework none
# Create a nest application inside the new project
ng g @nestjs/schematics:application apps/nest-app
# Nest application is ready to go
ng serve nest-app
ng test nest-app
ng build nest-app
```
  b. The `application` schematic right now is more of a `workspace` schematic as it brings in `.prettierrc`, `tsconfig.json`, etc. This makes it not only incompatible with Nx but also Angular CLI and other workspaces as well. My recommendation is to create a separate `new` schematic which would be used by `nest new` which handles everything but the `application` source code (`main.ts`). Below are the current conflicting files which we need to resolve and my suggestion on how to resolve them (biased as I work on Nx)
    i. `.prettierrc`
      a. I vote this moves to the `new` schematic and the one in the Nx workspace is used
    ii. `nodemon-debug.json`
      a. I vote this moves to the `new` schematic and the build in the Nx workspace is used
    iii. `nodemon.json`
      a. I vote this moves to the `new` schematic and the build in the Nx workspace is used
    iv. `package.json`
      a. I vote this moves to the `new` schematic and the one in the Nx workspace is used
    v. `README.md`
      a. I vote this moves to the `new` schematic and the one in the Nx workspace is used. I think currently the README.md is more of a workspace readme.md
    vi. `tsconfig.build.json`, `tsconfig.spec.json`, `tsconfig.json`
      a. These are tricky. Nest might be better suited to handle these because it could include types based on the type of application (`graphql`, `express`, etc). I would however look for an existing `tsconfig` file (The one Angular CLI and Nx makes is `tsconfig.app.json`) and alter that conservatively.
    ix. `tslint.json`
      a. This is also tricky. Nest might want to handle these because it could add some nest tslint rules. I would however look for an existing `tslint` file and alter that conservatively.
    x. `test` directory
      a. Nest should probably provide this however, I feel like there should be a flag for it. Nx currently does not `e2e` test `node-apps` directly and instead prefers to test the frontend app instead.

Sorry for the long wall of text. These are my thoughts at the moment but I'm open to suggestions.

**Comment by FrozenPandaz** [comment]
Given my previous comment, it was evident that the most complex part about this integration is the application schematic which Nx already has a lot of setup for. I've created a [PR](https://github.com/nrwl/nx/pull/974) to allow for
```sh
ng g node-app nest-app --framework nestjs # This is handled by Nx
ng g @nestjs/schematics:controller cats --source-root apps/nest-app/src --path app # This is handled by Nest Schematics
```

What do people here think about this? @kamilmysliwiec Thoughts?

**Comment by kamilmysliwiec** [comment]
Sounds good for me @FrozenPandaz + thanks for writing down your thoughts, I'll definitely provide a way to create an app without a workspace.

**Comment by jahumes** [comment]
So, I have been working on using nestjs with nx and am wondering why we are setting a default value for the source root by hard coding? Is there some way for us to have a configuration option to set the sourceRoot default?

**Comment by kamilmysliwiec** [comment]
> Is there some way for us to have a configuration option to set the sourceRoot default?

Yes, you can define the `sourceRoot` in the `nest-cli.json` (or `nest.json`). We'll provide more docs on this feature shortly.
