### ISSUE TITLE
Using async method and `ParseIntPipe` for generated resources controllers and services[restful] .

### ISSUE THREAD

**Issue by notzheng** [nestjs/schematics#1122]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

For now,  `nest g mo cat [restful]` will generated controllers like this:

```typescript
  @Get(':id')
 findOne(@Param('id') id: string) {
    return this.catService.findOne(+id);
  }
```

There is two problems I think:

1. use `+` to convert string to number
2. the method is sync, but usually we will get resources from db which be async

### Describe the solution you'd like

It would better to solve problem one using `ParseIntPipe` and make methods async.

```typescript
  @Get(':id')
   async findOne(@Param('id', ParseIntPipe) id: number) {
    return await this.catService.findOne(id);
  }
```

### What is the motivation / use case for changing the behavior?

as `related to a problem` part say.

**Comment by micalevisk** [comment]
you're problably using an old version. `@nestjs/cli@9` doesn't generate methods with `await` in it, I just tested

![image](https://user-images.githubusercontent.com/13461315/179968547-ae3fd54a-bcd8-40a6-bd60-4099b7773657.png)

But yeah, using `ParseIntPipe` is better

**Comment by notzheng** [comment]
> you're problably using an old version. `@nestjs/cli@9` doesn't generate methods with `await` in it
> 
> ![image](https://user-images.githubusercontent.com/13461315/179968547-ae3fd54a-bcd8-40a6-bd60-4099b7773657.png)
> 
> https://github.com/nestjs/schematics/blob/6d3a1be4df72725bf16e5765406755b2f521ac82/src/lib/resource/files/ts/__name__.controller.ts#L25-L27
> 
> But yeah, using `ParseIntPipe` is better
> 
> try `npx nest` instead of just `nest`

Sorry for misunderstanding caused by my typo. I have corrected it.

I mean it's better to generate async method in controller and service bucause usually we will get resources from db which be async (just my opinion) .

**Comment by micalevisk** [comment]
there's nothing sync in there, `findOne` returns the Promise. I prefer not having `return await` becaue is redundant (as there's no catch in there)

**Comment by micalevisk** [comment]
would you like to open a PR to add those `async` on them?

**Comment by notzheng** [comment]
> would you like to open a PR to add those `async` on them?

sorry for late, I'd like to do~

**Comment by notzheng** [comment]
> there's nothing sync here, `findOne` returns a promise, thus it's async. I prefer not having `return await` because is redundant (as there's no catch in there)

Hi, I have open a PR for this issue, but for `async` part only.

https://github.com/nestjs/schematics/pull/1163

I haven't use WebSocketGateway or graphQL Resolver  yet, but I see their method is also async in the [doc](https://docs.nestjs.com/graphql/resolvers#code-first-resolver), so I add `async` for them. If there is some problem, please let me know, and I will try to fix them.

---- 

And about the `ParseIntPipe` part.
I have no idea if it should change them, because: 
if user has enabled [auto-transformation](https://docs.nestjs.com/techniques/validation#transform-payload-objects), the `ValidationPipe` will perform conversion of primitive types, it should be 

```typescript
 @Get(':id')
 findOne(@Param('id') id: number) {
    return this.catService.findOne(id);
  }
```

But if user with `auto-transformation` disabled,  [Explicit conversion](https://docs.nestjs.com/techniques/validation#explicit-conversion)) will be better :

```typescript
  @Get(':id')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return await this.catService.findOne(id);
  }
```

so is there some way to know if user has `auto-transformation` enabled? 

Could you give me some advice?  and I'd like to open another PR.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schematics/pull/1163
