### ISSUE TITLE
Change tsconfig baseUrl from "./" to "./src"

### ISSUE THREAD

**Issue by myflowpl** [nestjs/schematics#122]
Is there any argument against this change ?

Building and testing still works as expected.

In `tsconfig.json` change `baseUrl` from `./` to `./src`
```typescript
{
  "compilerOptions": {
    "baseUrl": "./src"
  }
}
```

This will allow us to use absolute paths without `src` prefix:

BEFORE
```typescript
import { UserModel } from 'src/models';
```
AFTER CHANGE
```typescript
import { UserModel } from 'models';
```

file I'm talking about: https://github.com/nestjs/schematics/blob/master/src/lib/application/files/ts/tsconfig.json

**Comment by kamilmysliwiec** [comment]
Actually, both wouldn't work after compilation. I would suggest using (1) paths mapping (2) relative imports instead. `baseUrl` has been changed because we aim to support multirepo projects soon.
