### ISSUE TITLE
Upgrade peer dependency range to allow typescript v5

### ISSUE THREAD

**Issue by mcmxcdev** [nestjs/schematics#1354]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`@nestjs/schematics` is currently blocking users which have strict settings for peer dependencies from upgrading to TypeScript v5: 

```
.
├─┬ @nestjs/schematics 9.0.4
│ └── ✕ unmet peer typescript@^4.3.5: found 5.0.2
```

### Describe the solution you'd like

Review and merge PR created by renovate bot in https://github.com/nestjs/schematics/pull/1353 and bump up the allowed peer dependency range.

### What is the motivation / use case for changing the behavior?

Necessity to upgrade 3rd party libraries.

**Comment by rnkdsh** [comment]
+1

**Comment by GeSalla27** [comment]
+1

**Comment by zargham-leanix** [comment]
+1

**Comment by MuleaneEve** [comment]
I think that the ideal fix is:

```JSON
"peerDependencies": {
  "typescript": ">=4.3.5"
},
```

That way, we won't have this same issue when TypeScript 6 is released.

**Comment by kamilmysliwiec** [comment]
Updated "peerDependencies" in v9.1.0
