### ISSUE TITLE
error when invoking 'generate module' and there's no nestjs module to update

### ISSUE THREAD

**Issue by micalevisk** [nestjs/schematics#1444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when using `nest generate module` and there's no occurrence of `@Module()` of some `.module.ts` file at the entry dir, the CLI breaks with the following error:

```
Error: Cannot read properties of undefined (reading 'properties')

Failed to execute command: node @nestjs/schematics:module --name=foo --no-dry-run --no-skip-import --language="ts" --source-root="src" --no-spec --no-flat --spec-file-suffix="spec"
```

![image](https://github.com/nestjs/schematics/assets/13461315/fffbf4e3-2890-4437-a1a8-2be479ed20e9)

### Minimum reproduction code

https://gitlab.com/micalevisk/nestjs-schematics-issue-1444

### Steps to reproduce

1. `git clone https://gitlab.com/micalevisk/nestjs-schematics-issue-1444.git`
2. `cd nestjs-schematics-issue-1444`
3. `npm ci`
4. `npx nest g module foo`
5. see the error

the reason is pretty clear here:

https://github.com/nestjs/schematics/blob/e4d2c542eb08b3372c40f8a2393f166403eeb1a2/src/utils/metadata.manager.ts#L33-L37

those lines didn't cover the scenario of `decoratorNodes.length === 0`

### Expected behavior

The CLI should create the module without updating any other existing module, just like when there's no `.module.ts` file

### Package version

9.2.0

### Node.js version

18

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I tried to fix that already but didn't succeeded. I need more time to understand that `metadata.manager.ts`

**Comment by kamilmysliwiec** [comment]
Good catch! If you want to create a PR for this issue, that would be great! I believe adding a simple `if` condition should be enough(?)
