### ISSUE TITLE
Outdated schema file for nest-cli.json

### ISSUE THREAD

**Issue by lukemovement** [nestjs/schematics#1455]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

10

### Describe the regression

The schema at https://json.schemastore.org/nest-cli is out of date with version 10 of the cli package

![image](https://github.com/nestjs/schematics/assets/1868429/c7357594-f57a-409a-b0a3-5f85aa8d0411)

### Minimum reproduction code

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "builder": "swc",
    "typeChecking": true,
  }
}
```

### Expected behavior

For the correct options to not be flagged as invalid

**Comment by micalevisk** [comment]
feel free to open a PR in their repo: https://github.com/SchemaStore/schemastore see https://github.com/SchemaStore/schemastore/pull/3011

**Comment by micalevisk** [comment]
fixed in https://github.com/SchemaStore/schemastore/pull/3024

btw the option is `typeCheck`, not `typeChecking`
