### ISSUE TITLE
nest cli generate resource missing trailing comma

### ISSUE THREAD

**Issue by Lsnsh** [nestjs/schematics#1458]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

ESLint detected an error when opening `car.module.ts` file

### Minimum reproduction code

https://github.com/Lsnsh/mrc-world/tree/nestjs-schematics/nest-cli-generate-resource-missing-trailing-comma

### Steps to reproduce

1. `git clone git@github.com:Lsnsh/mrc-world.git -b nestjs-schematics/nest-cli-generate-resource-missing-trailing-comma`
2. `npm install`
3. `npx nest generate resource car`
   1. What transport layer do you use? `REST API`
   2. Would you like to generate CRUD entry points? `No`
4. open `./src/car/car.module.ts`
5. see the error 
![image](https://github.com/nestjs/schematics/assets/26019513/4a20c902-3738-4929-a7b5-19eec3ebe601)

### Expected behavior

No ESLint error when opening `car.module.ts` file

### Package version

10.0.1

### NestJS version

10.0.3

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

[System Information]
OS Version     : macOS 13.1 (22C65)
NodeJS Version : v18.16.0
PNPM Version    : 8.3.1 
Visual Studio Code: 1.79.2

[Nest CLI]
Nest CLI Version : 10.0.5 

[Nest Platform Information]
platform-express version : 10.0.3
mapped-types version     : 2.0.2
schematics version       : 10.0.1
testing version          : 10.0.3
common version           : 10.0.3
core version             : 10.0.3
cli version              : 10.0.5

**Comment by jmcdo29** [comment]
This is likely a quick update to the schematic in https://github.com/nestjs/schematics. Wanna take a crack at it?
