### ISSUE TITLE
Error when using 'application' generator in a directory that doesn't has the 'test' folder

### ISSUE THREAD

**Issue by micalevisk** [nestjs/schematics#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

you'll se following error when running `nest g app foo` in a dir that does not has the 'test' folder:

```
Error: Path "/test" does not exist.

Failed to execute command: node @nestjs/schematics:sub-app --name=foo --no-dry-run --no-skip-import --language="ts" --source-root="src" --spec --no-flat --spec-file-suffix="spec"
```

### Minimum reproduction code

see below

### Steps to reproduce

```bash
git clone git@github.com:nestjs/typescript-starter.git
cd typescript-starter
npm install @nestjs/cli@10.1.10
rm -rf test
npx nest g app foo
``` 

### Expected behavior

I think that the CLI shouldn't assume that every project will have a 'test' folder in their nestjs projects, so that command should went fine as when we have such folder

### Package version

10.0.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schematics/pull/1493
