### ISSUE TITLE
Project status & usage

### ISSUE THREAD

**Issue by Toub** [nestjs/schematics#15]
Hi guys, and good job here!

What is the status of this project regarding to https://github.com/nestjs/nest-cli

Which one to use right now? 

Status should be clarified in top of both projects, and integrated to the main documentation.

**Comment by ThomRick** [comment]
Hey @Toub,

Sorry for the long time before answer ! 

The schematics project is in develop phase to implement all https://github.com/nestjs/nest-cli usages (new / and generate) as  fix all bugs also.

After that it will be integrated to https://github.com/nestjs/nest-cli to replace the new / generate commands. ;-)

So for the moment you can use https://github.com/nestjs/nest-cli and waiting for the next versions to have bug fix and stable usages ;-)

**Comment by ThomRick** [comment]
You can use @nestjs/cli v4.0.0-rc1
