### ISSUE TITLE
use default library prefix

### ISSUE THREAD

**Issue by bejewelkyoungminkim** [nestjs/schematics#1562]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

when generate library, default prefix is always `@app`.
But it is boring to set company own prefix when generate library.
how about customizing default prefix?

### Describe the solution you'd like

make a new key for prefix in nest-cli.json
if key exists, use that prefix first, if not use @app

### Teachability, documentation, adoption, migration strategy

```
{
  ...
  "monorepo": true,
  "defaultLibraryPrefix": "@my-company"
}
```

### What is the motivation / use case for changing the behavior?

for convenience

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schematics/pull/1563
