### ISSUE TITLE
Generate CQRS Command/Query resource

### ISSUE THREAD

**Issue by horlaarsco** [nestjs/schematics#1790]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I started using CQRS recently on nestjs but when I need to generate a new Command or Query. I would have to create the file Command/Query and handler file, add the Command/Query to the module its in manually and then input the Command/query boilerplate I need to get started. As the project grows fast, it becomes repetitive and takes a little extra time.

### Describe the solution you'd like

Being able to generate Command/Query automatically the way we currently have for Resources/Controller etc

### What is the motivation / use case for changing the behavior?

I think this would make development faster and easier.

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
