### ISSUE TITLE
Make jest e2e config automaically discovered

### ISSUE THREAD

**Issue by aqeelat** [nestjs/schematics#1827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, the file is named jest-e2e.json, which is not in the naming scheme that jest expects. Therefore, running the tests in an IDE is not as easy as clicking the play button next to the test. Instead, we have to manually pass the config file to the IDE test runner. We can't also tell the IDE to always use this config file because then that would break the other tests.

I think that file should be renamed to jest.config.json so that it can be automatically picked up when running the tests under the test folder.

https://jestjs.io/docs/configuration

### Minimum reproduction code

https://github.com/nestjs/typescript-starter

### Steps to reproduce

1. `cd test`
2. `jest`

### Expected behavior

The tests should run using the config in the folder without having to explicitly pass it to it.

### Package version

10.1.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to change it in the foreseeable future.
