### ISSUE TITLE
Switch to strictNullChecks: true for new projects

### ISSUE THREAD

**Issue by dmint789** [nestjs/schematics#1934]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have realized that Nest JS sets up projects with `strictNullChecks: false` in the `tsconfig.json` by default. I was a bit of a beginner in web development when I first started using Nest JS, but I now see that this is not a good setting to use, because it leads to many bugs being missed. Now I have to migrate quite a big code base to `strictNullChecks: true`, which will cost me a lot of time.

### Describe the solution you'd like

This option should not be set in new Nest JS projects (meaning Typescript will treat it as true, since Nest JS sets `strict: true` for new projects).

### Teachability, documentation, adoption, migration strategy

This doesn't require developers having to relearn anything, because it would only apply to new Nest JS projects.

### What is the motivation / use case for changing the behavior?

This will prevent developers from having to migrate their code bases if they decided to change this setting in the future. If they wanted to set it to false, they could do so without having to change anything in the code, because that would be more permissive.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/schematics/pull/1945
