### ISSUE TITLE
Support path alias

### ISSUE THREAD

**Issue by ivgawev** [nestjs/schematics#1946]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Enable option to use the path alias and not the relative paths when creating a new component.

### Describe the solution you'd like

It could be an option in the nest-cli.json. For example, reading it from the tsconfig.json:

```json
{
  usePathAlias: true
}
```

or redeclaring it:

```json
{
  pathAlias: "@/*"
}
```

### What is the motivation / use case for changing the behavior?

I tend to use absolute paths with path aliases in general in all my projects and although it is not something that will make me stop using nestjs it is a more organized way, in my point of view, to have the imports.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
