### ISSUE TITLE
feature(javascript): Manage Javascript files

### ISSUE THREAD

**Issue by dario-rodriguez** [nestjs/schematics#31]
Now, when you use the application schematic, you only are able to create a Typescrit new project. Maybe if you add a parameter to choose between typescript and JavaScript will be useful for some ppl that dont want to use typescript. This is nothing strange, at nestjs official documentation you have a guide for this.

In my opinion, choose JavaScript instead typescript is a bad idea, but some ppl dont like or dont want to change to typescript. What is your opinion? It's just a suggestion and I want to know if you have any plan for JavaScript. 

Thx 4 ur time.

**Comment by ThomRick** [comment]
Hey @dario-rodriguez !

You totally right ! 
Javascript schematics will be developed later ! 
Need to focus on typescript part first to promote CLI usage with Nestjs.

**Comment by ThomRick** [comment]
Published in 5.3.0
