### ISSUE TITLE
Generate Resource Controllers

### ISSUE THREAD

**Issue by getspooky** [nestjs/schematics#367]
## Feature Request

Nestjs resource routing assigns the typical "CRUD" routes to a controller. For example, you may wish to create a controller that handles all HTTP requests for "cats" stored by your application.

## Is your feature request related to a problem? Please describe.

I am working on project with nestjs , so most of my work is related to create CRUD operations,
it would a good think to generate them.

## Describe the solution you'd like
you may use the `--resource` option when generating the Resource controller:
```sh
nest generate controller cats --resource
```

As a result The controller will contain a method for each of the available resource operations.
![carbon (2)](https://user-images.githubusercontent.com/37160072/80547567-d6442780-89b8-11ea-856b-427cce43b87a.png)

## What is the motivation / use case for changing the behavior?

A great feature that will help you save a lot of time!

**Comment by kamilmysliwiec** [comment]
We're planning to add such a schematic in the near future.

**Comment by getspooky** [comment]
@kamilmysliwiec 
Sure , i'm working on it.

**Comment by AlexHladin** [comment]
Hi, I've created PR that implement this functionality
@kamilmysliwiec, please review these PRs:

1. [#466](https://github.com/nestjs/schematics/pull/466)
2. [#849](https://github.com/nestjs/nest-cli/pull/849)

**Comment by kamilmysliwiec** [comment]
https://trilon.io/blog/introducing-cli-generators-crud-api-in-1-minute
