### ISSUE TITLE
Generate .gitignore when create ts project

### ISSUE THREAD

**Issue by ThomRick** [nestjs/schematics#76]
AS a user I WANT TO have a prepared .gitignore WHEN I use nest new command

How to demo :
  - execute schematics @nestjs/schematics:application --name=app
  - verify there is a .gitignore file

**Comment by overlineink** [comment]
Please, add `.gitignore` before install deps 📦! I do it manually, but consider fill this gap.
![nest](https://user-images.githubusercontent.com/24974840/52498598-288d0300-2bd1-11e9-88de-3065d579b031.jpg)

❤ Nest Framework
