### ISSUE TITLE
Warning about unsupported version of `@angular-devkit/core` on `LTS/gallium`

### ISSUE THREAD

**Issue by ddhorstman** [nestjs/schematics#847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When installing dependencies with the latest LTS version of Node.js (`16.13.0`), a warning appears related to angular installation:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@12.2.10',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@12.2.10',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics-cli@12.2.10',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.2' }
npm WARN EBADENGINE }
```

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/01-cats-app

### Steps to reproduce

1. Clone `nest`.
2. cd `sample/01-cats-app`
3. `npm i`

### Expected behavior

The package installs normally without any warnings.

### Package version

8.0.4

### NestJS version

8.1.2

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

This issue was discussed outside this repo [on this issue page](https://githubmemory.com/repo/nestjs/nest-cli/issues/1378).

**Comment by jmcdo29** [comment]
This is related to `@angular-devkit`. As it was recently released for v13, we'll be updating shortly. There's no impact on the functionality of the CLI or schematics, other than  getting the warning.

**Comment by ddhorstman** [comment]
No problem! Your automated version bumping failed because that release dropped the `jsonParse` utility - I opened this issue to link to in a [PR I opened to fix that issue](https://github.com/nestjs/schematics/pulls).
