### ISSUE TITLE
Strict mode by default

### ISSUE THREAD

**Issue by Sikora00** [nestjs/schematics#917]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I see most of the projects without the strict mode.

### Describe the solution you'd like

tsconfig.json
```tsconfig.json
"strict": true
```

### What is the motivation / use case for changing the behavior?

Angular currently generates new projects with the strict mode enabled by default. This should encourage people to apply best practices from the beginning. Angular case shows that people really follow the default configuration.
https://angular.io/guide/strict-mode

**Comment by micalevisk** [comment]
related with this https://github.com/nestjs/typescript-starter/pull/192#issuecomment-775900350

---

Personally, I prefer changing the default value of `strict` _option_ to `true`

https://github.com/nestjs/schematics/blob/cbb36a55c7f3e19b6fd9379bcf4ff82f4313fae4/src/lib/application/schema.json#L30-L34

that flag enables the following compiler options

https://github.com/nestjs/schematics/blob/cbb36a55c7f3e19b6fd9379bcf4ff82f4313fae4/src/lib/application/files/ts/tsconfig.json#L15-L19

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion @Sikora00!

This has been already discussed in the past, you can read more here https://github.com/nestjs/typescript-starter/pull/192#issuecomment-775900350
