### ISSUE TITLE
Error: This command can only be run inside of a CLI project.

### ISSUE THREAD

**Issue by simpulton** [nestjs/schematics#93]
The `generate` command does not work on a new project generated from the CLI as illustrated in the image below.

![wtut66qg](https://user-images.githubusercontent.com/590361/44247818-e348c500-a19b-11e8-88ee-0d7a183c7ea5.png)

**Comment by kamilmysliwiec** [comment]
`ng` is Angular CLI. Use `nest` instead :)

**Comment by simpulton** [comment]
Ahahahahah! But it looks and feels so much like Angular!

Sorry about that 😀 #muscleMemory
