### ISSUE TITLE
Schematics aliases

### ISSUE THREAD

**Issue by MoisesTR** [nestjs/schematics#935]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

**N/A**

### Describe the solution you'd like

Adding the corresponding aliases to `@nestjs/schematics`, so they will be available for whoever wants to extend from `@nestjs/schematics`

![Screen Shot 2022-02-08 at 12 33 39 PM](https://user-images.githubusercontent.com/23252442/153053013-569c27f0-d1b6-41d6-b42b-87355ced1eb2.png)

### Teachability, documentation, adoption, migration strategy

**N/A**

### What is the motivation / use case for changing the behavior?

I'm creating a custom **schematics** package and I'm extending from `@nestjs/schematics` in my collection.json to provide full support for both **schematics** generation, everything is working great, I'm able to generate my custom schematics as well as the `@nestjs/schematics` without having to specify the collection flag in the **Nest CLI**.

![Screen Shot 2022-02-08 at 10 38 41 AM](https://user-images.githubusercontent.com/23252442/153033155-7840705c-fe23-45a3-8a41-c51eed2b3a45.png)

The thing is, that since I have to set the collection property in the `nest-cli.json` to point to my **custom** schematics package, which is extending from `@nestjs/schematics`, this is so because it allows me to generate schematics that either belong to my custom schematics or `@nestjs/schematics` without the `-c` flag, but there is a limitation regarding the **Nest schematics generation**, aliases can't be used, because the aliases of the `@nestjs/schematics` don't exist, they are located in the `@nestjs/cli`, I think it would be helpful for whoever wants to extends from `@nestjs/schematics` to have those aliases available

![Screen Shot 2022-02-08 at 12 14 10 PM](https://user-images.githubusercontent.com/23252442/153050103-4cf84b76-d4a0-4ebc-ae54-9ad568cd2622.png)

**Comment by jmcdo29** [comment]
Seems like a straightforward enough enhancement. Would you like to make a PR for it?

**Comment by MoisesTR** [comment]
> Seems like a straightforward enough enhancement. Would you like to make a PR for it?

Sure thing, I'll take care of that 👍

**Comment by MoisesTR** [comment]
Hi @jmcdo29, I created the PR https://github.com/nestjs/schematics/pull/936, I tested the aliases locally and things are working

Should I tag you in the PR?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/schematics/pull/936
