### ISSUE TITLE
Gateway: output is generated in wrong directory

### ISSUE THREAD

**Issue by homj** [nestjs/schematics#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Motivation

My goal is to generate a gateway for specific entity / feature, e.g. `users`. All features lie within a `features` directory. So when generating NestJS elements for these features, I usually call something like this:

```sh
nest g controller features/users
```
or
```sh
nest g service features/users
```

For most cases this will generate the files in the `features/users` directory,

so the path of the controller would be `features/users/users.controller.ts`
and the path of the service `features/users/users.service.ts`

Both will be correctly registered in the existing `UsersModule` (`features/users/users.module.ts`)

## Issue

For gateways however, this command

```sh
nest g gateway features/users
```

will place the gateway at `features/users.gateway.ts` and register it in the `AppModule` instead.

## Workaround

To generate the gateway in the correct directory, you'd have to run

```sh
nest g gateway features/users/users
```

This different behavior from all other schematics makes it hard predict the outcome when using the cli and reduces the trust in how the CLI will modify the project. This can be irritating for new NestJS developers and such a special case is hard to remember, even for experienced devs.

## Console Output
Here's the console output from running the different schematics
![Bildschirmfoto 2022-02-23 um 17 14 08](https://user-images.githubusercontent.com/3742395/155360570-ba3a6264-2997-4a64-91be-6e6978fa2cd5.png)

### Minimum reproduction code

https://github.com/homj/nestjs-gateway-schematic-directory-bug

### Steps to reproduce

1. create a new nest application
2. create the users module: `nest g module features/users`
2. create the users module: `nest g controller features/users`
2. create the users module: `nest g service features/users`
3. create the users gateway `nest g gateway features/users`
4. the gateway will be placed in the wrong directory and registered in the `AppModule` instead of the `UsersModule`:

### Expected behavior

The gateway schematic should behave like all other schematics and output the gateway at the specified path.

### Package version

8.0.7

### NestJS version

8.3.1

### Node.js version

14.15.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I believe that option shouldn't be `true` by default as there's no way to switch to `false` from nestjs CLI.

```
$ nest generate --flat=false gateway a/b
Invalid schematic "false". Please, ensure that "false" exists in this collection.

$ nest generate --no-flat gateway a/b
error: unknown option '--no-flat'
```

**Comment by kamilmysliwiec** [comment]
This is intentional. We should allow setting it to false though (explicitly through flag or config)

**Comment by homj** [comment]
Thanks for the fast replies!

@kamilmysliwiec can you explain why this intentional and why it differs from the defaults of services or controllers?

**Comment by stanimirovv** [comment]
If no one is interested in adding the flag, I would gladly give it a go.

**Comment by micalevisk** [comment]
@stanimirovv you can go ahead :) ty

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest-cli/pull/1561
