### ISSUE TITLE
Generate resource command creates schema.gql file without the findAll Query that has been generated in the resolver

### ISSUE THREAD

**Issue by marywelch-chief** [nestjs/schematics#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

To reproduce:
Generate a resource with the CLI in a nestjs app using graphql.
```nest generate resource [resourceName]```

Compare the resolver with the schema.gql file.  The resolver has a query called findAll, but the gql schema does not include it as a query. 

Maybe there's something basic I'm missing, but why would something be created upon generation that is not usable?  I believe if it's not in the schema.gql file, you can't access it using the graphql playground.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-bhqprm?file=src/schema.gql

### Steps to reproduce

1. Open a terminal and run ```nest generate resource exampleResource```
2. When prompted, select 'GraphQL (code first)' as the transport layer
3. When prompted, select Y to generate CRUD entry points
4. Run ```npm run start:dev```
5. Review the generated schema.gql file.  Under type Query, there is no option to findAll for the exampleResource.

### Expected behavior

I would think the generation would create a "findAll" query in the graphQL schema, since it's already created a function in the resolver.

### Package version

10.0.7

### Graphql version

nestjs/cli: 8.2.3

        "@nestjs/apollo": "^10.0.7",
        "@nestjs/common": "^8.0.0",
        "@nestjs/core": "^8.0.0",
        "@nestjs/graphql": "^10.0.7",
        "@nestjs/platform-express": "^8.0.0",
        "@prisma/client": "^3.11.0",
        "apollo-server-express": "^3.6.4",

### NestJS version

8.0.0

### Node.js version

14.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by marywelch-chief** [comment]
I have updated the ticket with the reproduction repository and included steps for reproduction.

**Comment by kamilmysliwiec** [comment]
![image](https://user-images.githubusercontent.com/23244943/161262786-9d3d11d5-0687-41e4-8025-d6187b15b4dc.png)

> ? What name would you like to use for this resource (plural, e.g., "users")? 

And instead of passing `users`, you passed `user`.
