### ISSUE TITLE
Error message 'supertest_1.default is not a function' when starting e2e test

### ISSUE THREAD

**Issue by elgreco247** [nestjs/schematics#99]
The following error message is output when calling 'npm run test:e2e' in a newly generated nest.js app:

```    
    TypeError: supertest_1.default is not a function

      17 |
      18 |   it('/ (GET)', () => {
    > 19 |     return request(app.getHttpServer())
         |            ^
      20 |       .get('/')
      21 |       .expect(200)
      22 |       .expect('Hello World!');

      at Object.it (app.e2e-spec.ts:19:12)
```

The problem is fixed when replacing the `supertest` import in the e2e spec file to this:
```
import * as request from 'supertest';
```

**Comment by kamilmysliwiec** [comment]
Fixed in 5.7.0

**Comment by idemax** [comment]
still happening

**Comment by jmcdo29** [comment]
> still happening

The docs show `import * as request from 'supertest'` for a reason. Supertest does not use a default export. Unless you add `esModuleInterop: true` to your `tsconfig` you'll need to use the commonjs import syntax for Typescript. If you need further support, please visit our [Discord](https://discord.gg/nestjs)
